name: STOSC Bot

on:
  push:
    branches:
      - '*'

jobs:
  Build_and_Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  Deploy_to_VM:
    runs-on: ubuntu-latest
    needs: [ Build_and_Lint ]
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Remove unwanted folders
      run: |
        cd ${{ github.workspace }}
        rm -rf .git/ .github/ .gitignore

  
    - name: Stop the process and clear the folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: vibinjk
        key: ${{ secrets.KEY }}
        port: 22
        debug: false
        script: |
          ps -ef | grep 'run_stoscbot' | grep -v grep | awk '{print $2}' | xargs kill -9 2> /dev/null
          cd /home/vibinjk/stoscbot_pro
          rm -rf workspace/

    # Alternative: rsync -av -e ssh --delete --exclude='.git' --exclude='.session' --exclude='.session-journal' --exclude='.venv' --exclude='*.sh' --exclude='**/__pycache__' --exclude='.gitignore' --exclude='.env' --exclude='.vscode' . vibinjk@xxxx:/home/vibinjk/stoscbot          
    - name: Copy Files to Azure VM
      uses: horochx/deploy-via-scp@1.1.0
      with:
        local: ${{ github.workspace }}
        remote: /home/vibinjk/stoscbot_pro/
        host:  ${{ secrets.HOST }}
        port: 22
        user: vibinjk
        key: ${{ secrets.KEY }}
        # Ensure the existance of the remote file path
        ensureRemote: # optional

    - name: Install & Start the bot on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: vibinjk
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /home/vibinjk/stoscbot_pro/workspace
          cp ../credentials/* .
          cp ../credentials/.* .
          python3 -m venv .venv
          source .venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          nohup python3 run_stoscbot.py > /home/vibinjk/stoscbot_pro/logs/stoscbot.log 2>&1 &
