name: Build and Deploy STOSCBot

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  Build_Lint_Test_Coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@master
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-asyncio pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      env:
        STOSC_DB_HOST: ${{ secrets.STOSC_DB_HOST }}
        STOSC_DB_PWD: ${{ secrets.STOSC_DB_PWD }}
        STOSC_LOGS: ${{ secrets.STOSC_LOGS }}
        STOSC_TELEGRAM_BOT_TOKEN: ${{ secrets.STOSC_TELEGRAM_BOT_TOKEN }}
        STOSC_DDB_ACCESS_KEY_ID: ${{ secrets.STOSC_DDB_ACCESS_KEY_ID }}
        STOSC_DDB_SECRET_ACCESS_KEY: ${{ secrets.STOSC_DDB_SECRET_ACCESS_KEY }}
        STOSC_XERO_STOSC_TENANT_ID: ${{ secrets.STOSC_XERO_STOSC_TENANT_ID }}
        STOSC_XERO_CLIENT_ID: ${{ secrets.STOSC_XERO_CLIENT_ID }}
        SUPER_ADMIN_TELEGRAM_IDS: ${{ secrets.SUPER_ADMIN_TELEGRAM_IDS }}
        VIBIN_TELEGRAM_ID: ${{ secrets.VIBIN_TELEGRAM_ID }}
        CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER }}
        ENV: 'PRO'
        LOGLEVEL: 'INFO'
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  Version_Code:
    runs-on: ubuntu-latest
    needs: [ Build_Lint_Test_Coverage ]
    # Create versions only on this branch
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Application Versioning
      id: versioning
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}"
        namespace: ''
        bump_each_commit: true
        search_commit_body: true
        user_format_type: "csv"
    - name: "Update version file"
      run: |
        echo "[version]" > .VERSION
        echo "VERSION=${{ steps.versioning.outputs.version }}" >> .VERSION
        echo "BUILD=$GITHUB_SHA" >> .VERSION
        echo "RELEASE_DATE=$(TZ='Asia/Singapore' date +'%d-%m-%Y %r')" >> .VERSION
        echo "BRANCH=$GITHUB_REF_NAME" >> .VERSION
        cat .VERSION

    - name: Cache stoscbot for next Job
      id: cache-stoscbot
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}
        key: ${{ runner.os }}-stoscbot-${{ github.sha }}

  Deploy_to_VM:
    runs-on: ubuntu-latest
    needs: [ Version_Code ]
    if: ${{ true }}  # Keep this disabled or adjust as needed

    steps:
    - name: Get Cache for stoscbot workspace
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}
        key: ${{ runner.os }}-stoscbot-${{ github.sha }}

    - name: Set up Python 3.11
      uses: actions/setup-python@master
      with:
        python-version: "3.11"

    - name: Remove unwanted folders
      run: |
        cd ${{ github.workspace }}
        rm -rf .git/ .github/ .gitignore
        



    # See https://kamrul.dev/dynamically-add-github-actions-ip-to-aws-security-group/
    - name: Setting environment variables..
      if: env.CLOUD_PROVIDER == 'AWS'
      run: |
        echo "AWS_DEFAULT_REGION=ap-southeast-1" >> $GITHUB_ENV
        echo "AWS_SG_NAME=stosc-1-ec2" >> $GITHUB_ENV

    - name: Get Github action IP
      if: env.CLOUD_PROVIDER == 'AWS'
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Add Github Actions IP to Security group
      if: env.CLOUD_PROVIDER == 'AWS'
      run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}










    - name: Stop the bot and clear the folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BOT_HOST }}
        username: ${{ env.CLOUD_PROVIDER == 'Azure' && 'azureuser' || 'ubuntu' }}
        key: ${{ secrets.BOT_HOST_KEY }}
        port: 22
        script: |
          ps -ef | grep 'run_stoscbot' | grep -v grep | awk '{print $2}' | xargs kill -9 2> /dev/null
          cd ${{ env.CLOUD_PROVIDER == 'Azure' && '/home/azureuser/bots/stoscbot/workspace' || '/home/ubuntu/bots/stoscbot/workspace' }}
          rm -rf !\(.venv\)

    - name: Copy Files to VM
      uses: horochx/deploy-via-scp@1.1.0
      with:
        local: ${{ github.workspace }}
        remote: ${{ env.CLOUD_PROVIDER == 'Azure' && '/home/azureuser/bots/stoscbot/' || '/home/ubuntu/bots/stoscbot/' }}
        host:  ${{ secrets.BOT_HOST }}
        port: 22
        user: ${{ env.CLOUD_PROVIDER == 'Azure' && 'azureuser' || 'ubuntu' }}
        key: ${{ secrets.BOT_HOST_KEY }}

    - name: Install & Start the bot on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BOT_HOST }}
        username: ${{ env.CLOUD_PROVIDER == 'Azure' && 'azureuser' || 'ubuntu' }}
        key: ${{ secrets.BOT_HOST_KEY }}
        port: 22
        script: |
          cd ${{ env.CLOUD_PROVIDER == 'Azure' && '/home/azureuser/bots/stoscbot/workspace' || '/home/ubuntu/bots/stoscbot/workspace' }}
          cp ../credentials/* .
          cp ../credentials/.* .
          python -m venv .venv
          source .venv/bin/activate
          if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi
          nohup python run_stoscbot.py > /dev/null 2>&1 &







    - name: Remove Github Actions IP from security group
      if: env.CLOUD_PROVIDER == 'AWS'
      run: |
        aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
